# Generated by Django 4.2.5 on 2023-10-20 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_recipe_image_alter_savedrecipes_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='content',
            new_name='note_content',
        ),
        migrations.AlterField(
            model_name='notes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
